# Generated by Django 2.2.3 on 2019-07-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItems',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(blank=True, db_column='itemName', max_length=100, null=True)),
                ('lostPlace', models.CharField(blank=True, db_column='lostPlace', max_length=100, null=True)),
            ],
        ),
    ]
