# Generated by Django 2.2.3 on 2019-08-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitems',
            name='placeAddress',
            field=models.CharField(blank=True, db_column='placeAddress', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitemstemp',
            name='placeAddress',
            field=models.CharField(blank=True, db_column='placeAddress', max_length=100, null=True),
        ),
    ]
